export * from './dashboard/dashboard';
export * from './auth';
export * from './employees/employees';
export * from './add-employee/add-employee';
export * from './departments/departments';
export * from './add-department/add-department';
export * from './profile/profile';
export * from './reports/reports';
export * from './edit-profile/edit-profile';